; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-c3

[env:esp32-c3]
board = adafruit_qtpy_esp32c3
platform = espressif32
framework = arduino
lib_compat_mode = strict
board_build.filesystem = littlefs
monitor_speed = 115200
lib_deps =
	AsyncTCP@3.3.7
	ayushsharma82/ElegantOTA@^3.1.0
	bblanchon/ArduinoJson @ 6.19.4
	esp32async/ESPAsyncWebServer@3.7.3
	links2004/WebSockets@^2.6.1
	robtillaart/UUID@^0.2.0
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^3.11.0
build_flags =
	-D CHIP_FAMILY_RAW=\"ESP32-C3\"
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D RELAY_PIN=1
	-D FAN_PIN=4
	-D STATUS_LED_PIN=0
	-D TEMP_SENSOR_PIN=3
extra_scripts =
	pre:build_web.py
	merge_bin.py
